project_custom_fields:
  group: Grupo
  scheduled_start_date: Fecha de comienzo planificada
  scheduled_finish_date: Fecha de fin planificada
  scheduled_qa_meetings: Revision calidad planificada
  scheduled_role_effort: Esfuerzo previsto para {{role}}
  total_income: Cantidad aceptada
  actual_start_date: Fecha real de comienzo

reports:
  tracker: Informes
  custom_fields:
    held_qa_meetings: Revisi√≥n calidad realizada
    scheduled_finish_date: Fecha fin prevista
    scheduled_role_effort: Esfuerzo actual {{role}}

expenditures:
  tracker: Gastos
  custom_fields:
    initial_budget: Presupuesto inicial
    current_budget: Presupuesto actual
    incurred: Gasto del elemento
